# Generated by Django 4.2.13 on 2024-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('lyrics_summary', models.TextField(blank=True, null=True)),
                ('countries_mentioned', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
