# Generated by Django 5.0.6 on 2024-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
