# Generated by Django 5.0.6 on 2024-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='countries_mentioned',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='lyrics_summary',
            new_name='lyrics',
        ),
    ]
